version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(bun)"
    assignees:
      - "mqxym"
    target-branch: "mqxym/dev"

  - package-ecosystem: "github-actions"
    directory: "/"               
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    assignees:
      - "mqxym"
    target-branch: "mqxym/dev"

